name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  name: Minikube

variables:
- group: devops
- group: Surveyor
- name: version
  value: 0.2.0

stages:
- stage: Development
  jobs:
    - job: Build
      steps:
        - template: configure-version.yaml
        - template: configure-variables.yaml
         parameters:
           variables:
           - --password=$(password)
           - --app_version=$(version)
           - --test='Secret Password: Kubernetes'
           - --target=Publish Image
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            searchFolder: './artifacts/test-results/'
            testResultsFiles: '*.trx'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: './artifacts/helm/'
            ArtifactName: 'helm'
            publishLocation: 'Container'
    - job: Deployment
      dependsOn: Build
      condition: succeeded()
      steps:
        - template: configure-version.yaml
        - powershell: |
            echo "$(System.AccessToken)" | az devops login --organization $env:ENDPOINT_URL_SYSTEMVSSCONNECTION
            $projectVariables = az pipelines variable-group list --organization $env:ENDPOINT_URL_SYSTEMVSSCONNECTION --project $env:SYSTEM_TEAMPROJECT --group Surveyor | ConvertFrom-Json
            $options = @( 
              "--password=$(password)", 
              "--app_version=$(version)",
              "--test='Secret Password: Kubernetes'",
              "--target=Deploy Helm Chart"
            )
            $projectVariables.variables.PSObject.Properties | where {$_.Value.value -ne $null} | forEach { $options+= "--$($_.Name)=$($_.Value.value)"  }
            .\build.ps1 @options
          displayName: 'Run Cake Deployment Script'