name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  name: Minikube

resources:
  repositories:
  - repository: templates
    type: git
    name: templates

variables:
- group: devops
- group: Surveyor
- name: version
  value: 0.4.2

stages:
- stage: Development
  jobs:
    - job: Build
      steps:
        - template: configure-version.yaml@templates
        - template: run-cake.yaml@templates
          parameters:
           variables: "--docker_password=$(docker_password), --app_version=$(version), --target=Publish Image"
           library: Surveyor
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            searchFolder: './artifacts/test-results/'
            testResultsFiles: '*.trx'
    - job: Deployment
      dependsOn: Build
      condition: succeeded()
      steps:
        - template: configure-version.yaml@templates
        - template: run-cake.yaml@templates
          parameters:
           variables: "--app_version=$(version), --target=Deploy Helm Chart"
           library: Surveyor
