name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  name: Minikube

variables:
- group: devops
- group: Surveyor
- name: version
  value: 0.1.1

stages:
- stage: Dev
  jobs:
    - job: Build
      steps:
        - powershell: |
            if("$(Build.SourceBranchName)" -ne "main" ) { 
              Write-Host "##vso[task.setvariable variable=version]$(version)-$(Build.SourceBranchName).$(Build.BuildId)" 
            } else {
              Write-Host "##vso[build.updatebuildnumber]$(version)"
            }
          displayName: 'Configure Version'
        - powershell: |
            echo "$(pat)" | az devops login --organization https://dev.azure.com/magnoxium/
            $projectVariables = az pipelines variable-group list --organization https://dev.azure.com/magnoxium/ --project Andersoft --group Surveyor | ConvertFrom-Json
            $options = @( "--password=$(password)", "--app_version=$(version)" )
            $projectVariables.variables.PSObject.Properties | where {$_.Value.value -ne $null} | forEach { $options+= "--$($_.Name)=$($_.Value.value)"  }
            .\build.ps1 @options
          displayName: 'Run Cake Build Script'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            searchFolder: './artifacts/test-results/'
            testResultsFiles: '*.trx'