name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  name: Minikube

variables:
- group: devops
- group: Surveyor
- name: version
  value: 0.2.0

stages:
- stage: Development
  jobs:
    - job: Build
      steps:
        - template: configure-version.yaml
        - template: configure-cake.yaml
          parameters:
           variables: "--password=$(password), --app_version=$(version), --target=Publish Image"
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            searchFolder: './artifacts/test-results/'
            testResultsFiles: '*.trx'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: './artifacts/helm/'
            ArtifactName: 'helm'
            publishLocation: 'Container'
    - job: Deployment
      dependsOn: Build
      condition: succeeded()
      steps:
        - template: configure-version.yaml
        - template: configure-cake.yaml
          parameters:
           variables: "--password=$(password), --app_version=$(version), --test='Secret Password: Kubernetes', --target=Deploy Helm Chart"        