parameters:
- name: variables
  displayName: 'additional variables'
  type: object
  

steps:
  - powershell: |
      echo "$(System.AccessToken)" | az devops login --organization $env:ENDPOINT_URL_SYSTEMVSSCONNECTION
      $projectVariables = az pipelines variable-group list --organization $env:ENDPOINT_URL_SYSTEMVSSCONNECTION --project $env:SYSTEM_TEAMPROJECT --group Surveyor | ConvertFrom-Json
      $options = "${{ convertToJson(parameters.variables) }}" | ConvertFrom-Json
      $projectVariables.variables.PSObject.Properties | where {$_.Value.value -ne $null} | forEach { $options+= "--$($_.Name)=$($_.Value.value)"  }
      .\build.ps1 @options
    displayName: 'Run Cake Build Script'