apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-appsettings
  namespace: {{ include "service.namespace" . }}
data:
  appsettings.config.json: |-
{{ .Values.appsettings.config | b64dec | indent 4 }}
