apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:  {{ include "surveyor.namespace" . }}-gateway
  namespace: {{ include "surveyor.namespace" . }}
spec: 
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ include "surveyor.namespace" . }}/*"

