apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicechart.fullname" . }}-appsettings
  namespace: {{ include "servicechart.namespace" . }}
type: Opaque
stringData:
  appsettings.secrets.json: |-
{{ .Files.Get "appsettings.secrets.json" | indent 4 }}