replicaCount: 1

image:
  repository: andersoft/surveyor
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "surveyor"
fullnameOverride: "surveyor"

serviceAccount:
  create: true
  annotations: {}
  name: "surveyor"

service:
  type: ClusterIP
  port: 80
